version: '3.7'

services:
  php:
    container_name: auction
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/app
    ports:
      - ${NGINX_PORT}:80
    environment:
      env: "dev"
      XDEBUG_CONFIG: "remote_host=${DEBUG_IP} remote_enable=1"
      PHP_IDE_CONFIG: "serverName=auction"
      CONTAINER_ROLE: "app"
#  cron:
#    image: nexus.infra.toris.vpn:8091/upmm3-backend
#    container_name: upmm3-cron
#    build:
#      context: ./backend/
#      dockerfile: ./Dockerfile
#      args:
#        BUILD_DEV: ${BUILD_DEV}
#    depends_on:
#      - db
#    volumes:
#      - ./backend:/app
#    environment:
#      env: ${ENV}
#      XDEBUG_CONFIG: "remote_host=${DEBUG_IP} remote_enable=1"
#      PHP_IDE_CONFIG: "serverName=upmm3DockerCron"
#      CONTAINER_ROLE: "cron"
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: warstory_alexei
    volumes:
      - db:/var/lib/mysql
    ports:
      - ${PG_PORT}:3306
volumes:
  db:
